name: muvver
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  # dependencies injection
  get_it: ^7.2.0

  # places
  google_place: ^0.4.7
  uuid: ^3.0.6

  # layoult utilities
  auto_size_text: ^3.0.0
  flutter_typeahead: ^4.1.0

  # calendar
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker:
    git:
      url: https://github.com/Gabriel-S-Souza/flutter_rounded_date_picker
      ref: develop

  # formating
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 800
        - asset: assets/fonts/TitilliumWeb-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
